- title: true
- shields:
    style: 'flat-square'
    shields:
      - alt: 'flipactual'
        image: 'badge/😋-flipactual-218AC7.svg'
        link: 'https://www.flipactual.com/'
      - alt: 'Travis'
        image: 'travis/flipactual/pace-yourself.svg'
        link: 'https://travis-ci.org/flipactual/pace-yourself/'
      - alt: 'Codecov'
        image: 'codecov/c/github/flipactual/pace-yourself.svg'
        link: 'https://codecov.io/gh/flipactual/pace-yourself/'
      - alt: 'Node'
        image: 'node/v/pace-yourself.svg'
        link: 'http://npmjs.com/package/pace-yourself'
      - alt: 'NPM'
        image: 'npm/v/pace-yourself.svg'
        link: 'http://npmjs.com/package/pace-yourself'
- text: 'A priority queue and consumer'
- jsdoc: './src/PriorityQueue.js'
- jsdoc: './src/QueueConsumer.js'
- include: './docs/scripts.md'
- license: true
